services:
  - type: web
    name: zunny-pos
    runtime: node
    buildCommand: npm install
    startCommand: node zunny-pos-backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
